# Desafio Python e SQL

### Read com pd.read_sql

In [1]:
import pandas as pd
import sqlite3

conexao = sqlite3.connect("chinook.db") #cria a conexao com o banco de dados

tabela_clientes = pd.read_sql("SELECT *FROM customers", conexao) #faz a leitura do sql atraves do comando que selecionou tudo da tabela customers do banco de dados da conexao (2° parametro)

display(tabela_clientes[:3])

conexao.close()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3